use_frameworks!

platform :ios, '10.0'

target 'SwiftValidatorsReactiveExtensions_Example' do

  pod 'SwiftValidatorsReactiveExtensions', :path => '../'
  pod 'ReactiveCocoa'
  pod 'ReactiveSwift'

  target 'SwiftValidatorsReactiveExtensions_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
		pod 'Nimble', '~> 7.0.2'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
