use_frameworks!

target 'SwiftValidatorsReactiveExtensions_Example' do
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SwiftValidatorsReactiveExtensions', :path => '../'
  pod 'ReactiveCocoa'
  pod 'ReactiveSwift'

  target 'SwiftValidatorsReactiveExtensions_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
		pod 'Nimble', '~> 7.0.2'
  end
end
