use_frameworks!

platform :ios, '11.0'

target 'SwiftValidatorsReactiveExtensions_Example' do

    pod 'MagazineLayout'
    pod 'ReactiveCocoa'
    pod 'ReactiveSwift'
    pod 'SnapKit'
    pod 'SwiftValidatorsReactiveExtensions', :path => '../'

    target 'SwiftValidatorsReactiveExtensions_Tests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
